# Generated by Django 5.1.6 on 2025-02-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=255)),
                ('song_artist', models.CharField(max_length=255)),
                ('song_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('song_audio', models.FileField(blank=True, null=True, upload_to='audio/')),
            ],
        ),
    ]
